Repository FACG5/chat-it-out, pull requests merged in 2018-09, with the labels that each got.

#39 Doctors page
  package-lock.json
  package.json
  public/css/chat.css
  public/css/doctors.css
  public/css/footer.css
  public/css/public.css
  public/js/chat.js
  public/js/hamburger.js
  src/controllers/chat.js
  src/controllers/doctors.js
  src/controllers/index.js
  src/views/chat.hbs
  src/views/doctors.hbs
  src/views/layouts/main.hbs
  src/views/partials/aside.hbs
  src/views/partials/footer.hbs
  src/views/partials/head.hbs
  src/views/partials/header.hbs
  test/test_BE.js
Labels: awaiting-review

#46 DB Connection And Schema
  package-lock.json
  package.json
  src/model/database/db_build.js
  src/model/database/db_build.sql
  src/model/database/db_connection.js
  src/model/database/demo.sql
Labels: awaiting-review

#44 Home Page
  .gitignore
  public/css/home.css
  src/controllers/home.js
  src/controllers/index.js
  src/model/services.js
  src/views/home.hbs
  src/views/layouts/main.hbs
  test/test_BE.js
Labels: merge-ready

#47 Login and Sign Up
  .gitignore
  public/css/signUpIn.css
  public/js/sign-in.js
  public/js/sign-up.js
  src/controllers/index.js
  src/controllers/signIn.js
  src/controllers/signUp.js
  src/views/layouts/main.hbs
  src/views/sign-in.hbs
  src/views/sign-up.hbs
  test/test_BE.js
Labels: awaiting-review

#54 Articles page
  .travis.yml
  package-lock.json
  public/css/articles.css
  src/controllers/articles.js
  src/controllers/index.js
  src/model/queries/getData.js
  src/views/articles.hbs
  test/test_BE.js
Labels: awaiting-review

#64 Article page B.E
  public/css/articles.css
  src/controllers/article.js
  src/controllers/index.js
  src/model/queries/getData.js
  src/views/article.hbs
  src/views/articles.hbs
  test/test_BE.js
Labels: awaiting-review

#61 Sign Up BE
  .travis.yml
  package-lock.json
  package.json
  public/js/sign-up.js
  src/controllers/index.js
  src/controllers/signUp.js
  src/model/database/db_build.sql
  src/model/database/db_demo_build.js
  src/model/database/demo.sql
  src/model/queries/addUser.js
  test/test_BE.js
Labels: awaiting-review, priority-1

#63 Make links #62
  public/css/header.css
  src/controllers/articles.js
  src/views/partials/aside.hbs
  src/views/partials/header.hbs
Labels: awaiting-review, urgent

#65 Log In BE
  .travis.yml
  package.json
  public/js/sign-in.js
  public/js/sign-up.js
  src/app.js
  src/controllers/admin.js
  src/controllers/article.js
  src/controllers/doctors.js
  src/controllers/home.js
  src/controllers/index.js
  src/controllers/signIn.js
  src/middlewares.js
  src/model/queries/getUser.js
  src/views/partials/header.hbs
  src/views/sign-in.hbs
  test/test_BE.js
Labels: priority-1

#67 Error 404/500 page
  public/css/error.css
  src/controllers/error.js
  src/controllers/index.js
  src/views/error.hbs
Labels: merge-ready

#79 Chat Page
  .eslintrc.json
  package.json
  public/css/addDoctor.css
  public/css/admin.css
  public/css/article.css
  public/css/articles.css
  public/css/chat.css
  public/css/header.css
  public/css/home.css
  public/js/addArticle.js
  public/js/addDoctor.js
  public/js/chat.js
  public/js/home.js
  src/controllers/admin.js
  src/controllers/article.js
  src/controllers/articles.js
  src/controllers/chat.js
  src/controllers/doctors.js
  src/controllers/home.js
  src/controllers/index.js
  src/controllers/signOut.js
  src/controllers/suggestion.js
  src/index.js
  src/model/database/db_build.sql
  src/model/database/db_connection.js
  src/model/database/lastMessages.sql
  src/model/queries/addData.js
  src/model/queries/addMessage.js
  src/model/queries/addSuggestion.js
  src/model/queries/addUser.js
  src/model/queries/getAllUserMessages.js
  src/model/queries/getAllUsers.js
  src/model/queries/lastMessages.js
  src/model/services.js
  src/socketConfig.js
  src/views/admin.hbs
  src/views/chat.hbs
  src/views/home.hbs
  src/views/layouts/admin.hbs
  src/views/partials/aside.hbs
  src/views/partials/head.hbs
  src/views/partials/header.hbs
  src/views/sign-in.hbs
  src/views/sign-up.hbs
  src/views/viewSuggestions.hbs
  test/test_BE.js
Labels: awaiting-review

#73 doctor page #72
  public/css/doctor.css
  public/css/doctors.css
  src/controllers/article.js
  src/controllers/doctor.js
  src/controllers/index.js
  src/model/database/demo.sql
  src/model/queries/getData.js
  src/views/doctor.hbs
  src/views/doctors.hbs
Labels: awaiting-review

#75 Add doctor page
  public/css/addDoctor.css
  public/css/admin.css
  src/controllers/addDoctor.js
  src/controllers/index.js
  src/views/addDoctor.hbs
Labels: awaiting-review
